---
groups:
- name: main
  jobs:
  - deploy-job
resources:
- name: basic-express-site-2016
  type: git
  source:
    uri: https://github.com/vc4017/basic-express-site-2016.git
    branch: master

- name: cf-env
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: tovenki.ch@gmail.com
    password: Venki@521
    organization: concourse-node.js app
    space: deployment
    skip_cert_check: true

jobs:




- name: deploy-job
  serial: true
  plan:
  - {get: basic-express-site-2016, trigger: true}
  - put: cf-env
    params:
      manifest: basic-express-site-2016/manifest.yml
      path: basic-express-site-2016